language: php

php:
  - 7.2

before_script:
  - composer self-update
  - composer install --no-interaction

notifications:
  email:
    recipients:
      - wang84802@gmail.com
    on_success: always
    on_failure: always

script: ./vendor/bin/phpunit
